# Base image
FROM python:3.12

# Set the working directory
WORKDIR /app

# Copy requirements.txt (if you have one) and install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the entire app to the container
COPY . /app

# Expose the Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "visualize_space_science.py", "--server.port", "8080"]
